### ISSUE TITLE
Example Fails to Compile on Arduino IDE

### ISSUE THREAD

**Issue by rei-vilo** [mozilla-iot/http-on-off-mkr1000#6]
See https://discourse.mozilla.org/t/esp-adapter/26664/12

> The sketch at https://github.com/mozilla-iot/http-on-off-wifi101 no longer builds on the standard Arduino IDE.
> 
> <img width="500" alt="capture 2018-03-24 a 14 46 31" src="https://user-images.githubusercontent.com/951776/37864682-8d055a14-2f72-11e8-821a-9b4101c328ef.png">
> 
> The culprit seems to be the change introduced by `Remove ArduinoMDNS in favour of using PlatformIO one.` #5.
> 
> Please ensure the examples provided work with standard tools.

**Comment by rei-vilo** [comment]
I downloaded and installed PlatformIO. The sketch compiles, links and uploads but fails to run against the Arduino M0 Pro with the WiFi101 shield. 

I tried both `#define USE_MDNS_RESPONDER 0` and `#define USE_MDNS_RESPONDER 1`, to no avail. 

The previous release based on the WiFiMDNSResponder library works fine on the Arduino M0 Pro with the WiFi101 shield.

**Comment by dhylands** [comment]
Hmm. If you set USE_MDNS_RESPONDER to 1 then you should have exactly the previous version (to be specific version 6f94b90d046fdfbc1c81fcb78b06b6e918cbbeb9)

And if I do a git diff on hash 6f94b90d046fdfbc1c81fcb78b06b6e918cbbeb9 then all of the added code is in a #else on MDNS_RESPONDER.

**Comment by dhylands** [comment]
I added an http-on-off-wifi101.ino file to make it easier to build from within the Arduino IDE.
I also added instructions on how to install the Wifi101 and ArduinoMDNS dependencies inside the .ino file.
I built and tested this using Arduino 1.8.5 on my MKR1000 board and everything seems to be working fine,

**Comment by rei-vilo** [comment]
Thanks! I'll try on my Arduino Zero + WiFi 101.
